Try OCI CLI with instance principal auth if CLI config is not available

diff --git a/al-config-1.0/install/usr/sbin/al-config b/al-config-1.0/install/usr/sbin/al-config
--- a/al-config-1.0/install/usr/sbin/al-config
+++ b/al-config-1.0/install/usr/sbin/al-config
@@ -10,33 +10,38 @@
 
 usage() {
     cat >&2 << EOF
-Usage: $0 [OPTION]...
- -u OCI User OCID
- -t OCI tenancy OCID
- -T OCI notification service topic OCID
- -k OCI API key file
- -f OCI API public key fingerprint
- -p OCI API key pass phrase file
- -h This message
+Usage:
+
+  Confugre OCI notification service topic OCID:
+    ${0##*/} -T [topic OCID]
+
+  Configure OCI CLI:
+    ${0##*/} -u [user OCID] -t [tenancy OCID] -k [key file] -p [key passphrase file]
+
+  Options:
+    -T OCI notification service topic OCID
+    -u OCI User OCID
+    -t OCI Tenancy OCID
+    -k The file that we read API private key from
+    -p The file that we read API key passphrase from, provide this if API
+       private key is encrypted
+    -h Display this message
 EOF
     exit 1
 }
 
 run_as_root_check
 
-while getopts "u:k:p:f:t:T:h" OPTION; do
+while getopts "u:k:p:t:T:h" OPTION; do
     case "$OPTION" in
       u)
         oci_user=$OPTARG
         ;;
       k)
-        oci_key_file_from=$OPTARG
+        oci_api_private_key_from=$OPTARG
         ;;
       p)
-        oci_key_pass_phrase_from=$OPTARG
-        ;;
-      f)
-        oci_key_fingerprint=$OPTARG
+        oci_key_passphrase_from=$OPTARG
         ;;
       t)
         oci_tenancy=$OPTARG
@@ -53,64 +58,129 @@ while getopts "u:k:p:f:t:T:h" OPTION; do
     esac
 done
 
-if [ -z "$oci_user" -o -z "$oci_key_file_from" -o -z "$oci_key_fingerprint" -o \
-    -z "$oci_tenancy" -o -z "$oci_topic" ]; then
+# nothing provided
+if [ -z "$oci_topic" -a -z "$oci_user" -a -z "$oci_api_private_key_from" -a \
+    -z "$oci_tenancy" ]; then
     usage
 fi
 
-oci_key_file_content=$(read_file "$oci_key_file_from")
-if [ -z "$oci_key_file_content" ]; then
-    echo "Could not read $oci_key_file_from" >&2
-    exit 1
+# user, api praviate key, tenancy have to be provided together
+if [ -n "$oci_user" -o -n "$oci_api_private_key_from" -o -n \
+    "$oci_tenancy" ]; then
+    if [ -z "$oci_user" -o -z "$oci_api_private_key_from" -o -z \
+        "$oci_tenancy" ] ; then
+        usage
+    fi
 fi
 
-if [ -z "$oci_key_file_content" ]; then
-    echo "Could not read $oci_key_file_from" >&2
-    exit 1
-fi
+old_umask=$(umask)
 
-# It's ok that the key is not encrypted
-# So do not exit if key pass phrase file doesn't exit or empty
-if [ -n "$oci_key_pass_phrase_from" ]; then
-    oci_key_pass_phrase=$(read_file "$oci_key_pass_phrase_from")
-else
-    oci_key_pass_phrase=""
-fi
+### configure ###
 
-# initial config
-region=$(curl -sfm 25 \
-    http://169.254.169.254/opc/v1/instance/canonicalRegionName 2>/dev/null)
+## oci_cli.conf ##
+if [ -n "$oci_user" -a -n "$oci_api_private_key_from" -a \
+    -n "$oci_tenancy" ]; then
 
-cat > $oci_cli_config_file <<CONFIG
+    if [ ! -r "$oci_api_private_key_from" ]; then
+        echo "Could not read file $oci_api_private_key_from" >&2
+        exit 1
+    fi
+
+    oci_api_private_key=$(read_file "$oci_api_private_key_from")
+    if [ -z "$oci_api_private_key" ]; then
+        echo "Invalid private key in $oci_api_private_key_from" >&2
+        exit 1
+    fi
+
+    require_passphrase=0
+    # check if the private key is encrytped
+    # line 2: ^Proc-Type: 4,ENCRYPTED$
+    if sed -n '2 p' "$oci_api_private_key_from" | \
+        grep -q "^Proc-Type:.*ENCRYPTED$"; then
+        require_passphrase=1
+    fi
+
+    oci_key_passphrase=""
+    if [ $require_passphrase -eq 1 ]; then
+        if [ -z "$oci_key_passphrase_from" ]; then
+            echo "Key passphrase is required." >&2
+            exit 1
+        fi
+        if [ ! -r "$oci_key_passphrase_from" ]; then
+            echo "Could not read file $oci_key_passphrase_from" >&2
+            exit 1
+        fi
+        oci_key_passphrase=$(read_file "$oci_key_passphrase_from")
+    fi
+
+    # validate OCID
+    if [[ ! $oci_user =~ ^ocid[0-9]\.user\. ]]; then
+        echo "Invalid user OCID $oci_user" >&2
+        exit 2
+    fi
+    if [[ ! $oci_tenancy =~ ^ocid[0-9]\.tenancy\. ]]; then
+        echo "Invalid tenancy OCID $oci_tenancy" >&2
+        exit 2
+    fi
+    # calculate the public key fingerprint
+    if [ $require_passphrase -eq 1 ]; then
+        oci_key_fingerprint=$(openssl rsa -passin file:$oci_key_passphrase_from \
+            -pubout -outform DER -in $oci_api_private_key_from 2>/dev/null | \
+            openssl md5 -c | awk '{print $2}')
+    else
+        oci_key_fingerprint=$(openssl rsa -pubout -outform DER \
+            -in $oci_api_private_key_from 2>/dev/null | openssl md5 -c | \
+            awk '{print $2}')
+    fi
+
+    region=$(curl -sfm 25 \
+        http://169.254.169.254/opc/v1/instance/canonicalRegionName 2>/dev/null)
+
+    umask 0066
+    # oci_cli.conf
+    cat > $oci_cli_config_file <<CONFIG
 [DEFAULT]
 user = $oci_user
 key_file = $oci_api_key_file
 fingerprint = $oci_key_fingerprint
-pass_phrase = $oci_key_pass_phrase
+pass_phrase = $oci_key_passphrase
 tenancy = $oci_tenancy
 region = $region
 CONFIG
-chmod 600 $oci_cli_config_file
 
-# set api key
-echo "$oci_key_file_content" > $oci_api_key_file
-chmod 600 $oci_api_key_file
+    # oci_api_key.pem
+    cat > $oci_api_key_file <<KEYFILE
+    $oci_api_private_key
+KEYFILE
 
-log "Configured $oci_cli_config_file"
+    umask $old_umask
+    log "Configured OCI CLI."
+fi
 
-if [ ! -f "$oci_config_file" ]; then
-    cat > $oci_config_file <<EOF
+## oci.conf ##
+# topic is provided
+# set topic OCID to oci.conf
+if [ -n "$oci_topic" ]; then
+    if [[ ! $oci_topic =~ ^ocid[0-9]\.onstopic\. ]]; then
+        echo "Invalid notification service topic OCID $oci_topic" >&2
+        exit 2
+    fi
+    umask 0066
+    if [ ! -f "$oci_config_file" ]; then
+        cat > $oci_config_file <<EOF
 # This file is a bourne shell snippet, and is sourced by the
 # script al-notify for configuration.
 
 EOF
+    fi
+    if grep -q "^topic=" $oci_config_file; then
+        sed -i "s/^topic=.*/topic=$oci_topic/g" $oci_config_file
+    else
+        cat >> $oci_config_file <<EOF
+# OCI notification service topic OCID
+topic=$oci_topic
+EOF
+    fi
+    umask $old_umask
+    log "Configured OCI notification service topic OCID."
 fi
-
-# set topic OCID to oci.conf
-if grep -q "^topic=" $oci_config_file; then
-    sed -i "s/^topic=.*/topic=$oci_topic/g" $oci_config_file
-else
-    echo "# OCI notification service topic OCID" >> $oci_config_file
-    echo "topic=$oci_topic" >> $oci_config_file
-fi
-log "Configured $oci_config_file"
diff --git a/al-config-1.0/install/usr/sbin/al-notify b/al-config-1.0/install/usr/sbin/al-notify
--- a/al-config-1.0/install/usr/sbin/al-notify
+++ b/al-config-1.0/install/usr/sbin/al-notify
@@ -10,7 +10,7 @@
 
 usage() {
     cat >&2 << EOF
-Usage: $0 [OPTION]...
+Usage: ${0##*/} [OPTION]...
  -t Message title
  -f File that contains message body
  -h This message
@@ -22,17 +22,42 @@ EOF
 # $2 - title
 # $3 - body
 publish_message() {
-    local out ret
+    local out ret0 ret1 out0 out1
     log "Publishing message '$2'"
-    out=$($OCI ons message publish --topic-id "$1" --title "$2" --body "$3" \
-        2>&1)
-    ret=$?
-    if [ $ret -ne 0 ]; then
-        log_error "$out"
-        log_error "Failed to publish message '$2'"
-        return $ret
+    # oci config auth
+    if [ $instance_principal -eq 0 ]; then
+        out0=$($OCI_CONFIG_AUTH ons message publish --topic-id "$1" \
+            --title "$2" --body "$3" 2>&1)
+        ret0=$?
+        if [ $ret0 -ne 0 ]; then
+            # wait a second, we do second try with instance principal auth
+            sleep 1
+            out1=$($OCI_INSTANCE_PRINCIPAL_AUTH ons message publish \
+                --topic-id "$1" --title "$2" --body "$3" 2>&1)
+            ret1=$?
+            if [ $ret1 -ne 0 ]; then
+                log_error "Failed to publish message '$2'"
+                log_error "$out0"
+                log_error "$out1"
+                return $ret0
+            else
+                log "Published message '$2'"
+            fi
+        else
+            log "Published message '$2'"
+        fi
     else
-        log "Published message '$2'"
+        # instance principal auth
+        out1=$($OCI_INSTANCE_PRINCIPAL_AUTH ons message publish \
+            --topic-id "$1" --title "$2" --body "$3" 2>&1)
+        ret1=$?
+        if [ $ret1 -ne 0 ]; then
+            log_error "Failed to publish message '$2'"
+            log_error "$out1"
+            return $ret1
+        else
+            log "Published message '$2'"
+        fi
     fi
 }
 
@@ -62,10 +87,9 @@ if [ ! -f "$file" ]; then
     exit 1
 fi
 
-# If oci config, oci cli config or api key doesn't exist, exit.
-if [ ! -f "$oci_config_file" -o ! -f "$oci_cli_config_file" -o ! -f \
-    "$oci_api_key_file" ]; then
-    echo "OCI CLI is not properly configured." >&2
+# If oci config doesn't exist, exit.
+if [ ! -f "$oci_config_file" ]; then
+    echo "OCI notification service topic is not configured." >&2
     echo "Please run al-config to configure OCI CLI." >&2
     exit 2
 fi
@@ -80,14 +104,23 @@ if [ -z "$topic" ]; then
     exit 1
 fi
 
-OCI="oci --config-file $oci_cli_config_file"
+# If oci cli config or api key doesn't exist
+# switch to instance principal authorization
+if [ -f "$oci_cli_config_file" -a -f "$oci_api_key_file" ]; then
+    instance_principal=0
+else
+    instance_principal=1
+fi
+
+OCI_INSTANCE_PRINCIPAL_AUTH="oci --auth instance_principal"
+OCI_CONFIG_AUTH="oci --config-file $oci_cli_config_file"
 
 # oci cli check: get region subscription
-if ! $OCI iam region-subscription list &>/dev/null; then
-    echo "OCI CLI is not properly configured." >&2
-    echo "Please run al-config to configure OCI CLI." >&2
-    exit 2
-fi
+#if ! $OCI iam region-subscription list &>/dev/null; then
+#    echo "OCI CLI is not properly configured." >&2
+#    echo "Please run al-config to configure OCI CLI." >&2
+#    exit 2
+#fi
 
 size=$(stat -c %s $file)
 if [ $size -gt 65536 ]; then
@@ -100,9 +133,12 @@ if [ $size -gt 65536 ]; then
         log "Publishing message '$t'"
         body=$(read_file "$f")
         publish_message "$topic" "$t" "$body"
+        ret=$?
     done
     rm -f $files
 else
     body=$(read_file "$file")
     publish_message "$topic" "$title" "$body"
+    ret=$?
 fi
+exit $ret
