Remove compartment parameter and move notification topic to oci.conf

diff --git a/al-config-1.0/install/usr/sbin/al-config b/al-config-1.0/install/usr/sbin/al-config
--- a/al-config-1.0/install/usr/sbin/al-config
+++ b/al-config-1.0/install/usr/sbin/al-config
@@ -12,12 +12,11 @@ usage() {
     cat >&2 << EOF
 Usage: $0 [OPTION]...
  -u OCI User OCID
+ -t OCI tenancy OCID
+ -T OCI notification service topic OCID
  -k OCI API key file
  -f OCI API public key fingerprint
- -p OCI API key pass phrase if used
- -t OCI tenancy OCID
- -c OCI compartment name
- -n OCI notification service topic name
+ -p OCI API key pass phrase file
  -h This message
 EOF
     exit 1
@@ -25,7 +24,7 @@ EOF
 
 run_as_root_check
 
-while getopts "u:k:p:f:t:c:n:h" OPTION; do
+while getopts "u:k:p:f:t:T:h" OPTION; do
     case "$OPTION" in
       u)
         oci_user=$OPTARG
@@ -34,7 +33,7 @@ while getopts "u:k:p:f:t:c:n:h" OPTION; do
         oci_key_file_from=$OPTARG
         ;;
       p)
-        oci_key_pass_phrase=$OPTARG
+        oci_key_pass_phrase_from=$OPTARG
         ;;
       f)
         oci_key_fingerprint=$OPTARG
@@ -42,10 +41,7 @@ while getopts "u:k:p:f:t:c:n:h" OPTION; do
       t)
         oci_tenancy=$OPTARG
         ;;
-      c)
-        oci_compartment=$OPTARG
-        ;;
-      n)
+      T)
         oci_topic=$OPTARG
         ;;
       h)
@@ -58,7 +54,7 @@ while getopts "u:k:p:f:t:c:n:h" OPTION; do
 done
 
 if [ -z "$oci_user" -o -z "$oci_key_file_from" -o -z "$oci_key_fingerprint" -o \
-    -z "$oci_tenancy" -o -z "$oci_compartment" -o -z "$oci_topic" ]; then
+    -z "$oci_tenancy" -o -z "$oci_topic" ]; then
     usage
 fi
 
@@ -66,6 +62,19 @@ oci_key_file_content=$(read_file "$oci_key_file_from")
 if [ -z "$oci_key_file_content" ]; then
     echo "Could not read $oci_key_file_from" >&2
     exit 1
+fi
+
+if [ -z "$oci_key_file_content" ]; then
+    echo "Could not read $oci_key_file_from" >&2
+    exit 1
+fi
+
+# It's ok that the key is not encrypted
+# So do not exit if key pass phrase file doesn't exit or empty
+if [ -f "$oci_key_pass_phrase_from" ]; then
+    oci_key_pass_phrase=$(read_file "$oci_key_pass_phrase_from")
+else
+    oci_key_pass_phrase=""
 fi
 
 # initial config
@@ -87,14 +96,21 @@ chmod 600 $oci_cli_config_file
 echo "$oci_key_file_content" > $oci_api_key_file
 chmod 600 $oci_api_key_file
 
-# set compartment and topic name to al.conf
-if grep -q "^compartment=" $config_file; then
-    sed -i "s/^compartment=.*/compartment=$oci_compartment/g" $config_file
-else
-    echo "compartment=$oci_compartment" >> $config_file
+log "Configured $oci_cli_config_file"
+
+if [ ! -f "$oci_config_file" ]; then
+    cat > $oci_config_file <<EOF
+# This file is a bourne shell snippet, and is sourced by the
+# script al-notify for configuration.
+
+EOF
 fi
-if grep -q "^topic=" $config_file; then
-    sed -i "s/^topic=.*/topic=$oci_topic/g" $config_file
+
+# set topic OCID to oci.conf
+if grep -q "^topic=" $oci_config_file; then
+    sed -i "s/^topic=.*/topic=$oci_topic/g" $oci_config_file
 else
-    echo "topic=$oci_topic" >> $config_file
+    echo "# OCI notification service topic OCID" >> $oci_config_file
+    echo "topic=$oci_topic" >> $oci_config_file
 fi
+log "Configured $oci_config_file"
diff --git a/al-config-1.0/install/usr/sbin/al-notify b/al-config-1.0/install/usr/sbin/al-notify
--- a/al-config-1.0/install/usr/sbin/al-notify
+++ b/al-config-1.0/install/usr/sbin/al-notify
@@ -12,10 +12,28 @@ usage() {
     cat >&2 << EOF
 Usage: $0 [OPTION]...
  -t Message title
- -f File that contains message content
+ -f File that contains message body
  -h This message
 EOF
     exit 1
+}
+
+# $1 - topic id
+# $2 - title
+# $3 - body
+publish_message() {
+    local out ret
+    log "Publishing message '$2'"
+    out=$($OCI ons message publish --topic-id "$1" --title "$2" --body "$3" \
+        2>&1)
+    ret=$?
+    if [ $ret -ne 0 ]; then
+        log_error "$out"
+        log_error "Failed to publish message '$2'"
+        return $ret
+    else
+        log "Published message '$2'"
+    fi
 }
 
 run_as_root_check
@@ -44,23 +62,22 @@ if [ ! -f "$file" ]; then
     exit 1
 fi
 
-source_config_file
-
-# If topic or compartment is not set, exit.
-if [ -z "$topic" ]; then
-    echo "Please configure OCI notification service topic in $config_file." >&2
-    exit 1
-fi
-if [ -z "$compartment" ]; then
-    echo "Please configure OCI compartment name in $config_file." >&2
-    exit 1
-fi
-
-# If oci cli config or api key doesn't exist, exit.
-if [ ! -f "$oci_cli_config_file" -o ! -f "$oci_api_key_file" ]; then
+# If oci config, oci cli config or api key doesn't exist, exit.
+if [ ! -f "$oci_config_file" -o ! -f "$oci_cli_config_file" -o ! -f \
+    "$oci_api_key_file" ]; then
     echo "OCI CLI is not properly configured." >&2
     echo "Please run al-config to configure OCI CLI." >&2
     exit 2
+fi
+
+# source oci config file
+. $oci_config_file
+
+# If topic ocid is not set, exit.
+if [ -z "$topic" ]; then
+    echo "Please configure OCI notification service topic OCID in
+ $oci_config_file." >&2
+    exit 1
 fi
 
 OCI="oci --config-file $oci_cli_config_file"
@@ -72,52 +89,20 @@ if ! $OCI iam region-subscription list &>/dev/null; then
     exit 2
 fi
 
-# get comparment id
-compartment_id=$($OCI iam compartment list --all 2>/dev/null | \
-    jq -r ".data | .[]  | select(.\"name\" == \"$compartment\") | .\"id\"")
-if [ -z "$compartment_id" ]; then
-    echo "Could not find compartment $compartment OCID." >&2
-    echo "Please verify OCI compartment name in $config_file." >&2
-    exit 3
-fi
-
-# get topic id
-topic_id=$($OCI ons topic list --compartment-id $compartment_id --all \
-    2>/dev/null | jq -r ".data | .[]  | select(.\"name\" == \"$topic\") | \
-    .\"topic-id\"")
-
-if [ -z "$topic_id" ]; then
-    echo "Could not find topic $topic OCID." >&2
-    echo "Please verify OCI notification topic name in $config_file." >&2
-    exit 3
-fi
-
-multi_email=0
-files=$file
-count=0
 size=$(stat -c %s $file)
 if [ $size -gt 65536 ]; then
     split -C 64K -d -a 1 $file ${file}.
     files="$(ls $file.*)"
     count=$(ls $file.* | wc -l)
-    multi_email=1
-fi
-
-if [ $multi_email -eq 1 ]; then
-    for file in $files; do
-        index=${file##*.}
-        t="[$(($index+1))/$count] $title"
+    for f in $files; do
+        i=${f##*.}
+        t="[$(($i+1))/$count] $title"
         log "Publishing message '$t'"
-        message=$(read_file "$file")
-        $OCI ons message publish --topic-id $topic_id --title "$t" \
-            --body "$message" &&
-        log "Published message '$t'"
+        body=$(read_file "$f")
+        publish_message "$topic" "$t" "$body"
     done
     rm -f $files
 else
-    message=$(read_file "$file")
-    log "Publishing message '$title'"
-    $OCI ons message publish --topic-id $topic_id --title "$title" \
-        --body "$message" &&
-    log "Published message '$title'"
+    body=$(read_file "$file")
+    publish_message "$topic" "$title" "$body"
 fi
