Improve logic to determine whether to send notification.

diff --git a/al-config-1.0/install/usr/sbin/al-update b/al-config-1.0/install/usr/sbin/al-update
--- a/al-config-1.0/install/usr/sbin/al-update
+++ b/al-config-1.0/install/usr/sbin/al-update
@@ -6,8 +6,9 @@
 # al-update:
 # - yum-cron - yum upgrade
 # - ksplice kernel, user upgrade
+# - report ksplice all show
 # - report needs-restarting
-# - send notification
+# - send notification if needed
 
 . /usr/lib/al-config/functions
 
@@ -17,6 +18,39 @@ Usage: $0 [OPTION]...
  -h This message
 EOF
     exit 1
+}
+
+generate_message_title () {
+    local s=""
+    # default title:
+    local title="AL: Status update on instance $(hostname)"
+    # set titile to "updates installed"
+    if [ $status_ksplice_kernel = yes -o $status_ksplice_user = yes \
+         -o $status_yum = yes ]; then
+        if [ $status_ksplice_kernel = yes -o $status_ksplice_user = yes ]; then
+            s="Ksplice"
+            [ $status_yum = yes ] && s="Ksplice and Yum"
+            s="$s updates installed"
+        else
+            [ $status_yum = yes ] && s="Yum updates installed"
+        fi
+    fi
+    # set title to "upgrade failed"
+    if [ $status_ksplice_kernel = failed -o $status_ksplice_user = failed \
+         -o $status_yum = failed ]; then
+        if [ $status_ksplice_kernel = failed -o \
+             $status_ksplice_user = failed ]; then
+            s="Ksplice"
+            [ $status_yum = failed ] && s="Ksplice and Yum"
+            s="$s upgrade failed"
+        else
+            [ $status_yum = failed ] && s="Yum upgrade failed"
+        fi
+    fi
+
+    [ -n "$s" ] && title="AL: $s on instance $(hostname)"
+
+    echo "$title"
 }
 
 run_as_root_check
@@ -33,9 +67,6 @@ while getopts "h" OPTION; do
 done
 
 lock_file=/var/run/$(basename $0).lock
-
-source_config_file
-
 if [ -e $lock_file ]; then
     echo "$0 is already running." >&2
     echo "If you are sure it is not running, please delete $lock_file and re-run." >&2
@@ -43,26 +74,30 @@ if [ -e $lock_file ]; then
 fi
 touch $lock_file
 
-## status
-# ksplice kernel updates installed
-ksplice_kernel_installed=0
-# ksplice user updates installed
-ksplice_user_installed=0
-# yum updates installed
-yum_installed=0
+source_config_file
 
-# ksplice kernel upgrade failed
-ksplice_kernel_failed=0
-# ksplice user upgrade failed
-ksplice_user_failed=0
-# yum-cron failed
-yum_failed=0
+## status
+# Types of status:
+# 1. Updates installed: yes
+# 2. No updates installed: no
+# 3. Upgrade failed: failed
+
+# set default status to no
+status_yum=no
+status_ksplice_kernel=no
+status_ksplice_user=no
 
 # notify ?
 notify=0
 
-mkdir -p /var/run/al-config
-out_file=$(mktemp /var/run/al-config/al_msg_XXXX)
+# work dir
+work_dir=/var/run/al-config
+mkdir -p $work_dir
+
+# temp file that contains command outputs
+out_file=$(mktemp $work_dir/msg_XXXX)
+
+### Update starts ###
 
 # yum-cron
 echo "+------------------------------------------------------------------------+" | tee -a $out_file
@@ -70,13 +105,12 @@ echo "|  Yum upgrade report                                                    |
 echo "+------------------------------------------------------------------------+" | tee -a $out_file
 echo "Running 'yum-cron' with update cmd: default." | tee -a $out_file
 yum-cron $yum_cron_config_file 2>&1 | tee -a $out_file
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-    yum_failed=1
-fi
+[ ${PIPESTATUS[0]} -ne 0 ] && status_yum=failed
+
 # new updates - The updates were successfully applied
 # no new updates -
 if tail $out_file | grep -q "^The updates were successfully applied"; then
-    yum_installed=1
+    status_yum=yes
 fi
 
 # Pre-configure ksplice and yum for AL here
@@ -89,15 +123,14 @@ echo "|  Ksplice kernel upgrade report                                         |
 echo "+------------------------------------------------------------------------+" | tee -a $out_file
 echo "Running 'uptrack-upgrade -y'." | tee -a $out_file
 uptrack-upgrade -y 2>&1 | tee -a $out_file
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-    ksplice_kernel_failed=1
-fi
+[ ${PIPESTATUS[0]} -ne 0 ] && status_ksplice_kernel=failed
+
 # new updates: Installing
 # new rollback: Removing?
 # no new updates: Nothing to be done.
 if ! tail $out_file | grep -q "^Nothing to be done."; then
     if tail $out_file | egrep -q "^Installing|^Removing"; then
-        ksplice_kernel_installed=1
+        status_ksplice_kernel=yes
     fi
 fi
 
@@ -107,75 +140,80 @@ echo "|  Ksplice user-space upgrade report                                     |
 echo "+------------------------------------------------------------------------+" | tee -a $out_file
 echo "Running 'ksplice -y user upgrade'." | tee -a $out_file
 ksplice -y user upgrade 2>&1 | tee -a $out_file
-if [ ${PIPESTATUS[0]} -ne 0 ]; then
-    ksplice_user_failed=1
-fi
+[ ${PIPESTATUS[0]} -ne 0 ] && status_ksplice_user=failed
+
 # new package updates - Complete!
 # new live patches - Done!
 # no new updates - No packages marked for update
 #                  Nothing to do.
 if ! tail $out_file | grep -q "^Nothing to do."; then
     if egrep -q "^Complete!|^Done!" $out_file; then
-        ksplice_user_installed=1
+        status_ksplice_user=yes
     fi
 fi
+### Update is done ###
 
-# set notify and message titile
-title="AL: Status update on instance $(hostname)"
-s=""
-if [ $ksplice_kernel_installed -eq 1 -o $ksplice_user_installed -eq 1 -o $yum_installed -eq 1 ]; then
-    notify=1
-    if [ $ksplice_kernel_installed -eq 1 -o $ksplice_user_installed -eq 1 ]; then
-        s="Ksplice"
-        if [ $yum_installed -eq 1 ]; then
-            s="Ksplice and Yum"
-        fi
-        s="$s updates installed"
-    else
-        if [ $yum_installed -eq 1 ]; then
-            s="Yum updates installed"
-        fi
-    fi
-fi
+# Set notify
+# When do we notify?
+# 1. No yum, ksplice_kernel, ksplice_user updates: *Do Not Notify*
+#      1) *Notify If* there is no last update
+#         This means this is the first update, we want to notify with
+#         "Status update"
+#      2) *Notify If* - last update failed
+#         This means the failure has recovered, and we want to notify with
+#         "Status update".
+# 2. Yum, ksplice_kernel or ksplice_user updates installed: *Always Notify*
+# 3. Yum, ksplice_kernel or ksplice_user upgrade failed: *Notify*
+#      1) *Do Not Notify If* - failure is same as last update
+#         This means the failure has repeated, and we don't want to send
+#         duplicate notification.
+#
+# so we record every update
+# - update details for failures
+# - update status, yum, ksplice kernel and user-space
 
-# set title to "failed"
-if [ $ksplice_kernel_failed -eq 1 -o $ksplice_user_failed -eq 1 -o $yum_failed -eq 1 ]; then
-    notify=1
-    if [ $ksplice_kernel_failed -eq 1 -o $ksplice_user_failed -eq 1 ]; then
-        s="Ksplice"
-        if [ $yum_failed -eq 1 ]; then
-            s="Ksplice and Yum"
-        fi
-        s="$s upgrade failed"
-    else
-        if [ $yum_failed -eq 1 ]; then
-            s="Yum upgrade failed"
-        fi
-    fi
-fi
-
-if [ -n "$s" ]; then
-    title="AL: $s on instance $(hostname)"
-fi
-
-# if no state change, do not notify
-if cmp -s $out_file $al_state_file; then
+# 1. No yum, ksplice_kernel, ksplice_user updates: *Do Not Notify*
+if [ "$status_yum" = no -a "$status_ksplice_kernel" = no -a \
+     "$status_ksplice_user" = no ]; then
     notify=0
-else
-    notify=1
-    # update state
-    cp -f $out_file $al_state_file
+    # 1) *Notify If* there is no last update
+    # This means this is the first update, we want to notify with
+    # Status update"
+    [ ! -f "$al_state_file" -o ! -f "$al_update_file" ] &&
+        notify=1
+    # 2) *Notify If* - last update failed
+    #    This means the failure has recovered, and we want to notify with
+    #    "Status update".
+    [ -f "$al_state_file" ] && grep -q failed "$al_state_file" &&
+        notify=1
 fi
 
-# Create summary
-[ $yum_installed -eq 1 ] && s_yum="YES" || s_yum="NO"
-[ $yum_failed -eq 1 ] && s_yum="FAILED"
+# 2. Yum, ksplice_kernel or ksplice_user updates installed: *Always Notify*
+[ "$status_yum" = yes -o "$status_ksplice_kernel" = yes -o \
+     "$status_ksplice_user" = yes ] &&
+    notify=1
 
-[ $ksplice_kernel_installed -eq 1 ] && s_ksplice_kernel="YES" || s_ksplice_kernel="NO"
-[ $ksplice_kernel_failed -eq 1 ] && s_ksplice_kernel="FAILED"
+# 3. Yum, ksplice_kernel or ksplice_user upgrade failed: *Notify*
+if [ "$status_yum" = failed -o "$status_ksplice_kernel" = failed -o \
+     "$status_ksplice_user" = failed ]; then
+    notify=1
+    # 1) *Do Not Notify If* - failure is same as last update
+    #    This means the failure has repeated, and we don't want to send
+    #    duplicate notification.
+    [ -f "$al_update_file" ] && cmp -s $out_file $al_update_file &&
+        notify=0
+fi
 
-[ $ksplice_user_installed -eq 1 ] && s_ksplice_user="YES" || s_ksplice_user="NO"
-[ $ksplice_user_failed -eq 1 ] && s_ksplice_user="FAILED"
+# Update state file
+cat > $al_state_file <<EOF
+$(date)
+yum:$status_yum
+ksplice_kernel:$status_ksplice_kernel
+ksplice_user:$status_ksplice_user
+EOF
+
+# Record update details
+cp -f $out_file $al_update_file
 
 # Add summary
 summary_file=$out_file.summary
@@ -183,9 +221,9 @@ cat > $summary_file <<SUM
 +------------------------------------------------------------------------+
 |  Summary ($(date))                                |
 +------------------------------------------------------------------------+
-Yum updates installed: $s_yum
-Ksplice kernel updates installed: $s_ksplice_kernel
-Ksplice user-space updates installed: $s_ksplice_user
+Yum updates installed: $status_yum
+Ksplice kernel updates installed: $status_ksplice_kernel
+Ksplice user-space updates installed: $status_ksplice_user
 Uptime:$(uptime)
 
 SUM
@@ -221,8 +259,11 @@ echo "$summary"
 # send notification
 if [ $notify -eq 1 ]; then
     echo
+    title=$(generate_message_title)
     al-notify -t "$title" -f "$out_file"
 fi
+
+# update log
 cat $out_file >> $log_file
 rm -f $out_file
 
